[package]
name = "redisearch-api-rs"
version = "0.1.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[[example]]
name = "hello_redisearch"
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.1"
libc = "0.2"
time = "0.1"
enum-primitive-derive = "^0.1"
num-traits = "^0.2"
#failure = "0.1"

[build-dependencies]
bindgen = "0.51"
cc = "1.0"
