name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
    - name: Build
      run: cargo build --all --all-targets
    - name: Run tests
      run: cargo test --features test --all-targets
