name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodule
      run: |
        git submodule sync
        git submodule update --init
    - name: Install dependencies
      run: rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
    - name: Build
      run: cargo build --all --all-targets
    - name: Run tests
      run: cargo test --features test --all-targets
      
  build-freebsd:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        usesh: true
        sync: rsync
        prepare: pkg install -y bash gmake rust git clang
        run: |
          git submodule sync
          git submodule update --init
          rustup component add rustfmt
          cargo build --all --all-targets      
          cargo test --features test --all-targets
